version: '3.8'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node
    restart: unless-stopped
    command: tail -f /dev/null
    environment:
      - NODE_ENV=development
      - NITRO_PORT=4000
    ports:
      - 4000:4000
      - 8080:8080
    volumes:
      - ../..:/workspaces:cached

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    restart: unless-stopped
    ulimits:
      memlock: -1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: dragonfly --default_lua_flags=allow-undeclared-keys

  mongodb:
    image: mongo:7.0.6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  redis-data:
  mongodb-data:
